### ISSUE TITLE
Provide `arm64` build of `tsc-dyn.dylib` for Apple Silicon (M1) Macs

### ISSUE THREAD

**Issue by 3c1u** [emacs-tree-sitter/elisp-tree-sitter#88]
Currently, `tsc-dyn.dylib` has only `x86_64` binary.

```
✗ ~ file tsc-dyn.dylib 
tsc-dyn.dylib: Mach-O 64-bit dynamically linked shared library x86_64
```

`tsc-dyn.dylib` can be cross-compiled using the latest Rust toolchain.

**Comment by ubolonton** [comment]
This will likely need system toolchain for arm64 as well, in addition to Rust toolchain.
Then we will need someone with an M1 Mac to test it.

Have you been able to cross-compile it? Or do you have a link to a working guide for targeting `aarch64-apple-darwin` on `x86_64-apple-darwin`?

**Comment by 3c1u** [comment]
Tested on x86_64 macOS 11.1.

Use `master` branch of `tree-sitter` (`arm64` is now supported), and `emacs` crate with updated `bindgen` (libclang fails to load somehow otherwise)
```toml
emacs = { path = "../../emacs-module-rs" }
tree-sitter = { git = "https://github.com/tree-sitter/tree-sitter.git" }
```

and run this command:
```
env SDKROOT="/Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk" cargo build --all --release --target aarch64-apple-darwin
```
